title: Frailey Lawn Renewal
description: "Frailey Lawn Renewal provides expert lawn care services including seeding, dethatching, and weed prevention."
baseurl: "" # Leave blank for custom domains
url: "https://www.fraileylawnrenewal.com"
permalink: pretty
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tags
  - jekyll-sitemap

defaults:
  -
    scope:
      path: "assets"
    values:
      cache-control: "max-age=31536000, immutable"

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

