title: Frailey Lawn Renewal
description: "Grow a Thicker, Greener, Healthier Lawn"
baseurl: "" # Leave blank for custom domains
url: "https://www.fraileylawnrenewal.com"
theme: null

plugins:
  - jekyll-feed
  - jekyll-seo-tags
  - jekyll-sitemap